server:
  port: 8082

spring:
  application:
    name: api-gateway-vehicle-establishment
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: vehicle
              uri: http://localhost:8080
              predicates:
                - Path=/vehicle/**
              filters:
                - RewritePath=/vehicle(?<remaining>/?.*), /api/vehicles${remaining}

            - id: establishment
              uri: http://localhost:8081
              predicates:
                - Path=/establishment/**
              filters:
                - RewritePath=/establishment(?<remaining>/?.*), /api/establishment${remaining}
